=== alexCaste02/Lenguajes/Tema 5/actividad14_AlejandroCastellanos/empresas.dtd
<!ELEMENT empresas (grupo+)>
  <!ELEMENT grupo ((proveedores | clientes), empresa+)>
  <!ELEMENT proveedores (codigo, descripcion)>
  <!ELEMENT clientes (codigo, descripcion)>
  <!ELEMENT empresa (nombre, poblacion, provincia)>
    <!ATTLIST empresa id ID #REQUIRED>
  <!ELEMENT codigo (#PCDATA)>
  <!ELEMENT descripcion (#PCDATA)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT poblacion (#PCDATA)>
  <!ELEMENT provincia (#PCDATA)>
  <!ENTITY proveedores SYSTEM "proveedores.xml">
  <!ENTITY clientes SYSTEM "clientes.xml">
  <!ENTITY local SYSTEM "local.xml">
  <!ENTITY mu "Murcia">

=== alexCaste02/Lenguajes/Tema 5/actividad14_AlejandroCastellanos/listaempresas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresas SYSTEM "empresas.dtd">
<empresas>
  <grupo>
    &proveedores;
    <empresa id="p1">
      <nombre>Surinver</nombre>
      <poblacion>El Dorado</poblacion>
      <provincia>Aquella</provincia>
    </empresa>
    <empresa id="p2">
      <nombre>Don Simón</nombre>
      <poblacion>Jumilla</poblacion>
      <provincia>&mu;</provincia>
    </empresa>
  </grupo>
  <grupo>
    &clientes;
    <empresa id="c1">
      <nombre>Aráez</nombre>
      &local;
    </empresa>
    <empresa id="c2">
      <nombre>Venezuela</nombre>
      <poblacion>Lo Pagán</poblacion>
      <provincia></provincia>
    </empresa>
  </grupo>
</empresas>
