=== alexCaste02/Lenguajes/Tema 6/act14/productos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
 
  <xs:complexType name="dispositivo">
    <!--ESCRIBE AQUÍ EL CÓDIGO QUE FALTA-->
    
      <xs:sequence>
          <xs:element name="modelo" type="xs:string"/>
          <xs:element name="precio" type="xs:int"/>
          <xs:element name="ram" type="xs:int"/>
          <xs:element name="almacenamiento" type="xs:int"/>
        </xs:sequence>
     
  </xs:complexType>
  
  <xs:complexType name="pad">
    <!--ESCRIBE AQUÍ EL CÓDIGO QUE FALTA-->
    <xs:complexContent>
      <xs:extension base="dispositivo">
        <xs:simpleType>
         <xs:element name="pantalla"/>
        </xs:simpleType>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="pc">
   <!--ESCRIBE AQUÍ EL CÓDIGO QUE FALTA-->
   <xs:complexContent>
       <xs:extension base="dispositivo">
         <xs:element name="tarjetagrafica"/>
        </xs:extension>
      
    </xs:complexContent>
      </xs:complexType>
  
  <xs:element name="productos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="tablet" type="pad"/>
        <xs:element name="ordenador" type="pc"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== alexCaste02/Lenguajes/Tema 6/act14/productos.xml
<?xml version="1.0" encoding="UTF-8"?>
<productos xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
            xs:noNamespaceSchemaLocation="productos.xsd">
  <tablet>
    <modelo>Samsung galaxy Tab S6</modelo>
    <precio>299</precio>
    <ram>4</ram>
    <almacenamiento>64</almacenamiento>
    <pantalla>10.4</pantalla>
  </tablet>
  <ordenador>
    <modelo>PcCom Silver</modelo>
    <precio>1027</precio>
    <ram>16</ram>
    <almacenamiento>1024</almacenamiento>
    <tarjetagrafica>GeForce GTX 1660</tarjetagrafica>
  </ordenador>
</productos>
