=== alexCaste02/Lenguajes/Tema 5/albaranes.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT albaran (numero,fecha,cliente,articulos)>
<!ELEMENT numero #PCDATA #REQUIRED>
<!ELEMENT fecha #PCDATA #REQUIRED>
<!ELEMENT cliente (nombre,poblacion)
<!ATTLIST cliente id CDATA #REQUIRED>
<!ELEMENT nombre #PCDATA #REQUIRED>
<!ELEMENT poblacion #PCDATA #REQUIRED>
<!ELEMENT articulos (compra+)>
<!ELEMENT compra (articulo,cantidad)>
<!ELEMENT articulo (descripcion|botella|granel|precio)*>
<!ELEMENT descripcion CDATA #REQUIRED>
<!ELEMENT botella EMPTY>
<!ELEMENT granel EMPTY>
<!ELEMENT precio #PCDATA>


<!ELEMENT cantidad #PCDATA>






<!ELEMENT jugador EMPTY>
<!ATTLIST jugador nombre NMTOKENS #REQUIRED>
<!ATTLIST jugador codigo ID #REQUIRED>
<!ELEMENT equipo EMPTY>
<!ATTLIST equipo nombre CDATA #REQUIRED>
<!ATTLIST equipo jugadores IDREFS #IMPLIED>

=== alexCaste02/Lenguajes/Tema 5/albaran6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE albaran SYSTEM "albaranes.dtd">
<albaran>
    <numero>6</numero>
    <fecha>2021-10-02</fecha>
    <cliente id="15">
        <nombre>María Fuentes</nombre>
        <poblacion>San Pedro del Pinatar</poblacion>        
    </cliente>
    <articulos>
        <compra>
            <articulo codigo="9">
                <descripcion>Vino blanco. Viña Serea 75 cl</descripcion>
                <botella/>
                <precio>0.85</precio>
            </articulo>
            <cantidad>15</cantidad>
            <descuento>5%</descuento>
        </compra>        
    </articulos>    
</albaran>

=== alexCaste02/Lenguajes/Tema 5/albaran8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE albaran SYSTEM "albaranes.dtd">
<albaran>
    <numero>8</numero>
    <fecha>2011-10-03</fecha>
    <cliente id="1">
        <nombre>Francisco García</nombre>
        <poblacion>Orihuela</poblacion>        
    </cliente>
    <articulos>
        <compra>
            <articulo codigo="9">
                <descripcion>Vino Valdepeñas gran reserva. Viña Albali 75cl</descripcion>
                <botella/>
                <precio>4.98</precio>
            </articulo>
            <cantidad>3</cantidad>
        </compra>                
        <compra>
            <articulo codigo="12">
                <descripcion>Vino tinto Rioja reserva. Marques de Riscal 75 cl</descripcion>
                <botella/>
                <precio>12.85</precio>
            </articulo>
            <cantidad>1</cantidad>
        </compra>
        <compra>
            <articulo codigo="58">
                <descripcion>Vino Ribera de Duero crianza. Valpicia 75 cl</descripcion>
                <botella/>
                <precio>5,49</precio>
            </articulo>
            <cantidad>1</cantidad>
        </compra>                        
    </articulos>    
</albaran>

=== alexCaste02/Lenguajes/Tema 5/albaran7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE albaran SYSTEM "albaranes.dtd">
<albaran>
    <numero>7</numero>
    <fecha>2021-10-03</fecha>
    <cliente id="15">
        <nombre>Pepe Gonz√°lez</nombre>
        <poblacion>Torrevieja</poblacion>        
    </cliente>
    <articulos>
        <compra>
            <articulo codigo="0">
                <descripcion>Vino a granel</descripcion> 
                <granel/>
                <precio>0.10</precio>
            </articulo>
            <cantidad>5</cantidad>
        </compra>        
    </articulos>    
</albaran>

=== alexCaste02/Lenguajes/Tema 5/albaran5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE albaran SYSTEM "albaranes.dtd">
<albaran>
    <numero>5</numero>
    <fecha>2021-10-02</fecha>
    <cliente id="1">
        <nombre>Pedro García</nombre>
        <poblacion>Pilar de la Horadada</poblacion>
    </cliente>
    <articulos>
        <compra>
            <articulo codigo="12">
                <descripcion>Vino tinto Rioja reserva. Marques de Riscal 75 cl</descripcion>
                <botella/>
                <precio>12.85</precio>
            </articulo>
            <cantidad>2</cantidad>
        </compra>
        <compra>
            <articulo codigo="12">
                <descripcion>Vino Blanco D.O.Penedès. Vinya Sol Torres 75 cl</descripcion>
                <botella/>
                <precio>4.80</precio>
            </articulo>
            <cantidad>1</cantidad>
        </compra>        
    </articulos>    
</albaran>
