=== alexCaste02/Lenguajes/Tema 5/matricula.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT matricula (ciclo, alumnado)>
<!ELEMENT ciclo (#PCDATA)>
<!ELEMENT alumnado (alumno)>
<!ELEMENT alumno (nombre,anyo,modulos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>
<!ELEMENT modulos (modulo+)>
<!ELEMENT modulo (#PCDATA)>

=== alexCaste02/Lenguajes/Tema 5/ACT3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE matricula SYSTEM "matricula.dtd">
<matricula>
  <ciclo>Desarrollo de Aplicaciones Multiplataforma</ciclo>
  <alumnado>
    <alumno>
      <nombre>Francisco Parra</nombre>
      <anyo>2021</anyo>
      <modulos>
        <modulo>Lenguajes de marcas</modulo>
        <modulo>Entornos de desarrollo</modulo>
      </modulos>
    </alumno>
  </alumnado>
</matricula>
