=== alexCaste02/Lenguajes/Tema 5/personal.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT personal (persona)+>
<!ELEMENT persona (datos,email*,url*,relacion?)>
  <!ATTLIST persona id ID #REQUIRED>
  <!ATTLIST persona salario CDATA #IMPLIED>
<!ELEMENT datos ((apellido,nombre)|(nombre,apellido))>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT url EMPTY>
  <!ATTLIST url href CDATA 'http://'>
<!ELEMENT relacion EMPTY>
  <!ATTLIST relacion director IDREF #IMPLIED>
  <!ATTLIST relacion trabajador IDREFS #IMPLIED>

=== alexCaste02/Lenguajes/Tema 5/actividad13_AlejandroCastellanos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personal SYSTEM "personal.dtd">
<personal>

  <persona id="d" salario="50">
    <datos>
      <nombre>Alberto</nombre>
      <apellido>Martinez</apellido>
    </datos>
    <email>albmar99@gmail.com</email>
    <url href="http://aules.edu.gva.es/fp/mod/assign/view.php?id=2630695"/>
    <relacion trabajador="t1 t2 t3"/>
  </persona>
  
  <persona id="t1" salario="25">
    <datos>
      <nombre>Bruno</nombre>
      <apellido>Perez</apellido>
    </datos>
    <email>bruper00@gmail.com</email>
    <email>bruper00@hotmail.es</email>
    <url href="http://www.stylusstudio.com/SSDN"/>
    <relacion director="d"/>
  </persona>
  
  <persona id="t2" salario="30">
    <datos>
      <nombre>Carmelo</nombre>
      <apellido>Sanchez</apellido>
    </datos>
    <email>bruper00@gmail.com</email>
    <email>bruper00@hotmail.es</email>
    <url href="http://www.stylusstudio.com/SSDN"/>
  
  </persona>
  
  <persona id="t3" >
    <datos>
      <nombre>David</nombre>
      <apellido>Gomez</apellido>
    </datos>
    <email>bruper00@gmail.com</email>
    <email>bruper00@hotmail.es</email>
    <url href="http://www.stylusstudio.com/SSDN"/>
    <relacion director="d"/>
  </persona>
  
</personal>
