=== alexCaste02/Lenguajes/Tema 6/act15/equipos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsi:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema">

	<xsi:simpleType name="cantidad">
		<xsi:restriction base="xsi:int">
			<xsi:minInclusive value="7"/>
			<xsi:maxInclusive value="30"/>
		</xsi:restriction>
	</xsi:simpleType>
	
	<xsi:simpleType name="tipociclista">
		<xsi:restriction base="xsi:string">
			<xsi:enumeration value="clasicomana"/>
			<xsi:enumeration value="esprinter"/>
			<xsi:enumeration value="escaladora"/>
			<xsi:enumeration value="vueltomana"/>
		</xsi:restriction>
	</xsi:simpleType>

	<xsi:element name="equipo">
		<xsi:complexType >
			<xsi:sequence>
				<xsi:element name="nombre" type="xsi:string"/>
				<xsi:element name="nacionalidad" type="xsi:string"/>
				<xsi:element name="cantidadciclistas" type="cantidad"/>
				<xsi:element name="marcabici" type="xsi:string"/>
				<xsi:choice>
					<xsi:element name="uci"/>
					<xsi:element name="protour"/>
				</xsi:choice>
				<xsi:element name="direccion">
					<xsi:complexType>
						<xsi:sequence>
							<xsi:element name="director" maxOccurs="3">
								<xsi:complexType>
									<xsi:sequence>
										<xsi:element name="nombre" type="xsi:string"/>
										<xsi:element name="apellido" type="xsi:string"/>
									</xsi:sequence>
								</xsi:complexType>
							</xsi:element>
						</xsi:sequence>
					</xsi:complexType>
				</xsi:element>
				<xsi:element name="ciclistas" >
					<xsi:complexType>
						<xsi:sequence>
							<xsi:element name="ciclista" minOccurs="7" maxOccurs="30">
								<xsi:complexType mixed="true">
									<xsi:sequence>
										<xsi:element name="nombre" type="xsi:string"/>
										<xsi:element name="apellido" type="xsi:string"/>
										<xsi:choice>
											<xsi:element name="edad" type="xsi:int"/>
											<xsi:element name="nacimiento" type="xsi:date"/>
										</xsi:choice>
										<xsi:element name="puntos" type="xsi:int" minOccurs="0"/>
									</xsi:sequence>
									<xsi:attribute name="tipo" type="tipociclista"/>
								</xsi:complexType>
							</xsi:element>
						</xsi:sequence>
					</xsi:complexType>
				</xsi:element>
			</xsi:sequence>
		</xsi:complexType>
	</xsi:element>
	
</xsi:schema>

=== alexCaste02/Lenguajes/Tema 6/act15/planturpura.xml
<?xml version="1.0" encoding="UTF-8"?>
<equipo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="equipos.xsd">
            <nombre>Plantur Pura</nombre>
            <nacionalidad>Bélgica</nacionalidad>
            <cantidadciclistas>7</cantidadciclistas>
            <marcabici>Stevens</marcabici>
            <uci/>
            <direccion>
              <director>
                <nombre>Heidi</nombre>
                <apellido>Van De Vijver</apellido>
              </director>
              <director>
                <nombre>Philip</nombre>
                <apellido>Roodhooft</apellido>
              </director>
            </direccion>
            <ciclistas>
              <ciclista tipo="clasicomana">
                <nombre>Ceylin del Carmen</nombre>
                <apellido>Alvarado</apellido>
                <edad>22</edad>
                <puntos>6</puntos>
              </ciclista>
              <ciclista tipo="esprinter">
                <nombre>Puck</nombre>
                <apellido>Pieterse</apellido>
                <edad>19</edad>
              </ciclista>
              <ciclista tipo="escaladora">
                <nombre>Annemarie</nombre>
                <apellido>Worst</apellido>
                <nacimiento>1995-12-19</nacimiento>
                <puntos>5</puntos>
              </ciclista>
              <ciclista tipo="vueltomana">
                <nombre>Yara</nombre>
                <apellido>Kastelijn</apellido>
                <edad>23</edad>
                <puntos>77</puntos>
              </ciclista>
              <ciclista tipo="esprinter">
                <nombre>Inge</nombre>
                <apellido>Van der Heijden</apellido>
                <nacimiento>1999-08-12</nacimiento>
                <puntos>46</puntos>
              </ciclista>
              <ciclista tipo="clasicomana">
                <nombre>Marthe</nombre>
                <apellido>Truyen</apellido>
                <edad>21</edad>
                <puntos>16</puntos>
              </ciclista>
              <ciclista tipo="vueltomana">
                <nombre>Sanne</nombre>
                <apellido>Cant</apellido>
                <nacimiento>1990-10-08</nacimiento>
              </ciclista>
            </ciclistas>
  </equipo>
